[package]
name = "memol_gui"
edition = "2021"
build = "build.rs"

[dependencies]
gumdrop = "*"
gl = "*"
glutin = "0.29.*"
image = { version = "*", default-features = false, features = ["jpeg", "png"] }
copypasta = "*"
memol = { path = "../memol" }
memol_util = { path = "../memol_util" }

[build-dependencies]
cc = "*"
bindgen = "*"
