[package]
name = "memol_gui"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]
build = "build.rs"

[dependencies]
getopts = "*"
gl = "*"
glutin = "*"
image = "*"
memol = { path = "../memol" }
memol_cli = { path = "../memol_cli" }

[build-dependencies]
cc = "*"
bindgen = "*"

[target.'cfg(windows)'.build-dependencies]
winres = "*"
