[package]
name = "memol_gui"
edition = "2021"
build = "build.rs"

[dependencies]
gumdrop = { version = "*", default-features = false }
gl = { version = "*", default-features = false }
glutin = { version = "0.29.*", default-features = false, features = ["wayland", "wayland-dlopen"] }
image = { version = "*", default-features = false, features = ["jpeg", "png"] }
memol = { path = "../memol" }
memol_util = { path = "../memol_util" }

[build-dependencies]
cc = { version = "*", default-features = false }
bindgen = { version = "*", default-features = false, features = ["runtime"] }
