[package]
name = "memol_gui"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]
build = "build.rs"

[dependencies]
getopts = "*"
gl = "*"
glutin = "*"
memol = { path = "../memol" }

[build-dependencies]
gcc = "*"
bindgen = "*"

[target.'cfg(windows)'.dependencies]
libloading = "*"
