group: travis_latest
language: rust

matrix:
    include:
        - os: linux
          env: TARGET=x86_64-unknown-linux-gnu
          script:
              - CC=clang CXX=clang++ cargo build --release --target=${TARGET}
              - cd target/${TARGET}/release
              - mv libmemol_vst.so memol_vst.so
              - strip --strip-all memol_cli memol_gui memol_vst.so
              - 7z a memol-${TARGET}.zip memol_cli memol_gui memol_vst.so
        - os: linux
          env: >-
              TARGET=aarch64-unknown-linux-gnu
              CFLAGS="--sysroot=/usr/aarch64-linux-gnu -isystem /usr/aarch64-linux-gnu/include"
              CXXFLAGS="--sysroot=/usr/aarch64-linux-gnu -isystem /usr/aarch64-linux-gnu/include"
          script:
              - sed -i 's|bindgen::Builder::default()|bindgen::Builder::default().clang_arg( "--sysroot=/usr/aarch64-linux-gnu" ).clang_arg( "-isystem" ).clang_arg( "/usr/aarch64-linux-gnu/include" )|' memol_gui/build.rs
              - rustup target add ${TARGET}
              - CC=clang CXX=clang++ cargo build --release --target=${TARGET} --lib
              - CC=clang CXX=clang++ cargo build --release --target=${TARGET} --bin memol_cli
              - cd target/${TARGET}/release
              - mv libmemol_vst.so memol_vst.so
              - aarch64-linux-gnu-strip --strip-all memol_cli memol_vst.so
              - 7z a memol-${TARGET}.zip memol_cli memol_vst.so
        - os: linux
          env: TARGET=x86_64-pc-windows-gnu
          script:
              - rustup target add ${TARGET}
              - CC=clang CXX=clang++ cargo build --release --target=${TARGET}
              - cd target/${TARGET}/release
              - x86_64-w64-mingw32-strip --strip-all memol_cli.exe memol_gui.exe memol_vst.dll
              - 7z a memol-${TARGET}.zip memol_cli.exe memol_gui.exe memol_vst.dll
        - os: osx
          env: TARGET=x86_64-apple-darwin
          script:
              - brew install p7zip curl
              - CC=clang CXX=clang++ cargo build --release --target=${TARGET}
              - cd target/${TARGET}/release
              - mv libmemol_vst.dylib memol_vst.dylib
              - strip memol_cli memol_gui
              - 7z a memol-${TARGET}.zip memol_cli memol_gui memol_vst.dylib

addons:
    apt:
        packages:
            - gcc-mingw-w64-x86-64
            - gcc-aarch64-linux-gnu
            - libc-dev-arm64-cross
            - p7zip-full

deploy:
    provider: releases
    api_key:
        secure: HV0gqtrpybiKdeVJilJenM9wrMXzJU6vnh2hXXRUsxpvvhWinZR2c76lq3gsZNrRzMilc3jx8HZ+rbbToUUFacyJGGqUboKAhIewVO9Q1/Ow5c0dQCkgNXmNMEwOc7tkXfjSlbVa14eLsbdOXq5tQfou/J1jNKPX6xxrCgYIEafS+Soo7l9Qd/zqGHsbvGdvYDBOK/UdMP7y/TkKor0NgZnj+IVZK1xv8gMlv4x2tlYHMGMPWR2cW5T0afJpOdT8mFXHyou9JWwl30jYqzZgak01jN2ji/pIpG5Ii9zin/HS8dKws/1MNqIDJLqNChuyxVf0qln6Gx88S92DaaKq2Lh4yOgMdFsAB4y6DwYSSBO16bj2WrQ5kF7e9o9HZ3KUh++x7sgiDD4Px7ivfYX5jnSMzELGW3PIp7IzQYvTsCh7CV0I2IhxhFvwhVfqLpBw2nQEQ8TJk9rMWGx/etwFXNyjGDBUgNSyqaBtAUz4EketoiepQ6aRDBj8BBnj+aX/7vl9oTnAHXa9Y6moVGy4JnsQY3PUjd+jlzPPJN2BQS9SMf/fHACD6tfsjQoLxM0L6oXfCiTtPswlW1rxcishDQvAGlmBmtGwEX2SndDYD0V+n27FZ3aO1A7k4wZmpBkXpchy1BkmoXx934mc9TUM12XZnYTtmIBlfI7xCIz//tc=
    file: memol-${TARGET}.zip
    skip_cleanup: true
