group: travis_latest
osx_image: xcode9.2

language: rust

matrix:
    include:
        - os: linux
          env: >-
              TARGET=x86_64-unknown-linux-gnu
              EXEC_SUFFIX=
              STRIP="strip --strip-all"
              SED_INPLACE="sed -i"
        - os: linux
          env: >-
              TARGET=aarch64-unknown-linux-gnu
              EXEC_SUFFIX=
              STRIP="aarch64-linux-gnu-strip --strip-all"
              SED_INPLACE="sed -i"
        - os: linux
          env: >-
              TARGET=x86_64-pc-windows-gnu
              EXEC_SUFFIX=.exe
              STRIP="x86_64-w64-mingw32-strip --strip-all"
              SED_INPLACE="sed -i"
        - os: osx
          env: >-
              TARGET=x86_64-apple-darwin
              EXEC_SUFFIX=
              STRIP=strip
              SED_INPLACE="sed -i ''"
    allow_failures:
        - os: osx
        - os: linux
          env: >-
              TARGET=aarch64-unknown-linux-gnu
              EXEC_SUFFIX=
              STRIP="aarch64-linux-gnu-strip --strip-all"
              SED_INPLACE="sed -i"

addons:
    apt:
        packages:
            - gcc-mingw-w64-x86-64
            - gcc-aarch64-linux-gnu
            - libc-dev-arm64-cross
            - p7zip-full

script:
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install p7zip curl; fi
    - rustup target add aarch64-unknown-linux-gnu
    - rustup target add x86_64-pc-windows-gnu

    - ${SED_INPLACE} 's/<Windows\.h>/<windows.h>/g' memol_gui/imgui/imgui.cpp

    - CC=clang CXX=clang++ cargo build --release --target=${TARGET}
    - cd target/${TARGET}/release
    - ${STRIP} memol${EXEC_SUFFIX}
    - ${STRIP} memol_gui${EXEC_SUFFIX}
    - 7z a memol-${TARGET}.zip memol${EXEC_SUFFIX} memol_gui${EXEC_SUFFIX}

    - curl --upload-file memol-${TARGET}.zip https://transfer.sh/memol-${TARGET}.zip || true
