group: travis_latest

language: rust

matrix:
    include:
        - os: linux
          env: >-
              STRIP=strip
              TARGET=x86_64-unknown-linux-gnu
              EXEC_SUFFIX=
        - os: linux
          env: >-
              STRIP=aarch64-linux-gnu-strip
              TARGET=aarch64-unknown-linux-gnu
              EXEC_SUFFIX=
        - os: linux
          env: >-
              STRIP=x86_64-w64-mingw32-strip
              TARGET=x86_64-pc-windows-gnu
              EXEC_SUFFIX=.exe
        - os: osx
          env: >-
              STRIP=strip
              TARGET=x86_64-apple-darwin
              EXEC_SUFFIX=
    allow_failures:
        - os: osx

addons:
    apt:
        packages:
            - gcc-mingw-w64-x86-64
            - gcc-aarch64-linux-gnu
            - libc-dev-arm64-cross
            - p7zip-full
            - curl

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip curl; fi
    - rustup target add aarch64-unknown-linux-gnu
    - rustup target add x86_64-pc-windows-gnu

    - CC=clang CXX=clang++ cargo build --release --target=${TARGET}
    - cd target/${TARGET}/release
    - ${STRIP} --strip-all memol${EXEC_SUFFIX}
    - ${STRIP} --strip-all memol_gui${EXEC_SUFFIX}
    - 7z a memol-${TARGET}.zip memol${EXEC_SUFFIX} memol_gui${EXEC_SUFFIX}

    - curl --upload-file memol-${TARGET}.zip https://transfer.sh/memol-${TARGET}.zip || true
