group: travis_latest
osx_image: xcode9.2

language: rust

matrix:
    include:
        - os: linux
          env: >-
              TARGET=x86_64-unknown-linux-gnu
              EXEC_SUFFIX=
              STRIP="strip --strip-all"
        - os: linux
          env: >-
              TARGET=aarch64-unknown-linux-gnu
              CFLAGS="--sysroot=/usr/aarch64-linux-gnu -isystem /usr/aarch64-linux-gnu/include"
              CXXFLAGS="--sysroot=/usr/aarch64-linux-gnu -isystem /usr/aarch64-linux-gnu/include"
              EXEC_SUFFIX=
              STRIP="aarch64-linux-gnu-strip --strip-all"
        - os: linux
          env: >-
              TARGET=x86_64-pc-windows-gnu
              EXEC_SUFFIX=.exe
              STRIP="x86_64-w64-mingw32-strip --strip-all"
        - os: osx
          env: >-
              TARGET=x86_64-apple-darwin
              EXEC_SUFFIX=
              STRIP=strip
    allow_failures:
        - os: osx
        - os: linux
          env: >-
              TARGET=aarch64-unknown-linux-gnu
              CFLAGS="--sysroot=/usr/aarch64-linux-gnu -isystem /usr/aarch64-linux-gnu/include"
              CXXFLAGS="--sysroot=/usr/aarch64-linux-gnu -isystem /usr/aarch64-linux-gnu/include"
              EXEC_SUFFIX=
              STRIP="aarch64-linux-gnu-strip --strip-all"

addons:
    apt:
        packages:
            - gcc-mingw-w64-x86-64
            - gcc-aarch64-linux-gnu
            - libc-dev-arm64-cross
            - p7zip-full

script:
    - |
        case "${TARGET}" in
            "x86_64-apple-darwin" )
                brew install p7zip curl
            ;;
            "x86_64-pc-windows-gnu" )
                rustup target add x86_64-pc-windows-gnu
                sed -i 's|<Windows\.h>|<windows.h>|g' memol_gui/imgui/imgui.cpp
            ;;
            "aarch64-unknown-linux-gnu" )
                rustup target add aarch64-unknown-linux-gnu
                sed -i 's|bindgen::Builder::default()|bindgen::Builder::default().clang_arg( "--sysroot=/usr/aarch64-linux-gnu" ).clang_arg( "-isystem" ).clang_arg( "/usr/aarch64-linux-gnu/include" )|' memol_gui/build.rs
            ;;
        esac

    - CC=clang CXX=clang++ cargo build --release --target=${TARGET}
    - cd target/${TARGET}/release
    - ${STRIP} memol${EXEC_SUFFIX}
    - ${STRIP} memol_gui${EXEC_SUFFIX}
    - 7z a memol-${TARGET}.zip memol${EXEC_SUFFIX} memol_gui${EXEC_SUFFIX}

    - curl --upload-file memol-${TARGET}.zip https://transfer.sh/memol-${TARGET}.zip || true
