group: travis_latest
osx_image: xcode9.2

language: rust

matrix:
    include:
        - os: linux
          env: >-
              TARGET=x86_64-unknown-linux-gnu
              EXEC_SUFFIX=
              STRIP="strip --strip-all"
        - os: linux
          env: >-
              TARGET=aarch64-unknown-linux-gnu
              CFLAGS="--sysroot=/usr/aarch64-linux-gnu -isystem /usr/aarch64-linux-gnu/include"
              CXXFLAGS="--sysroot=/usr/aarch64-linux-gnu -isystem /usr/aarch64-linux-gnu/include"
              EXEC_SUFFIX=
              STRIP="aarch64-linux-gnu-strip --strip-all"
        - os: linux
          env: >-
              TARGET=x86_64-pc-windows-gnu
              EXEC_SUFFIX=.exe
              STRIP="x86_64-w64-mingw32-strip --strip-all"
        - os: osx
          env: >-
              TARGET=x86_64-apple-darwin
              EXEC_SUFFIX=
              STRIP=strip
    allow_failures:
        - os: osx
        - os: linux
          env: >-
              TARGET=aarch64-unknown-linux-gnu
              CFLAGS="--sysroot=/usr/aarch64-linux-gnu -isystem /usr/aarch64-linux-gnu/include"
              CXXFLAGS="--sysroot=/usr/aarch64-linux-gnu -isystem /usr/aarch64-linux-gnu/include"
              EXEC_SUFFIX=
              STRIP="aarch64-linux-gnu-strip --strip-all"

addons:
    apt:
        packages:
            - gcc-mingw-w64-x86-64
            - gcc-aarch64-linux-gnu
            - libc-dev-arm64-cross
            - p7zip-full

script:
    - |
        case "${TARGET}" in
            "x86_64-apple-darwin" )
                brew install p7zip curl
            ;;
            "x86_64-pc-windows-gnu" )
                rustup target add x86_64-pc-windows-gnu
                sed -i 's|<Windows\.h>|<windows.h>|g' memol_gui/imgui/imgui.cpp
            ;;
            "aarch64-unknown-linux-gnu" )
                rustup target add aarch64-unknown-linux-gnu
                sed -i 's|bindgen::Builder::default()|bindgen::Builder::default().clang_arg( "--sysroot=/usr/aarch64-linux-gnu" ).clang_arg( "-isystem" ).clang_arg( "/usr/aarch64-linux-gnu/include" )|' memol_gui/build.rs
            ;;
        esac

    - CC=clang CXX=clang++ CARGO_INCREMENTAL=0 cargo build --release --target=${TARGET}
    - cd target/${TARGET}/release
    - ${STRIP} memol_cli${EXEC_SUFFIX}
    - ${STRIP} memol_gui${EXEC_SUFFIX}
    - 7z a memol-${TARGET}.zip memol_cli${EXEC_SUFFIX} memol_gui${EXEC_SUFFIX}

deploy:
    provider: releases
    api_key:
        secure: Sic6McEifxATx/a60AYGiEgm1e9fPUdElkNBzqfsyLrrdAqMriF8hLKf+tXp4/BIooZNhVdwRWl8lW9aGqVVpe5Vx/ELVRvVsPNXRVp5C/eRsMC7tW4HL3Pw4vGNrn/bG8R0Uu2DH5/ZLeIrp0S1PNpbSDFTk1GMNx8FPxkvalU7FakpiXI6wsRF3WqdaTo24Jz6G8hYbzz4aALauyYXLoKOYecQASpHQneOFTGQE42H6gpkmIrbcXaidx4IJHs+uiVSmAoCsTEvqSEptWmOcT3lzJ23WKPQfR8CFf5gT/alUjyTdzq0t990Sj8SSKenFB/VfdSLY/HKTWk0Q1EgXi2pE8X04hsepGm7+1Z4MsoajO4gcfqWvHA7HAp1CVITVuiZx48lTMHSyPrqagPnymsNDvuhOFkIutR1UO+chDhlmKDtkHjLFhz1S3LhiBM0BUENrwsPBrPCxkEK6t1EyKZYanXSbDqwWvyP3tz1JMFRlPKNUbx6E6vuVyUGmFbnbaWunrGIdiwfjfjDg7yEzNRnsHeyFuVuuJqzNvxhtwt+XXNpLBgZSdVydOOZ0NrMA47uYHTksG45elAIJ85aZQ8zth2j9V0VCOVBcHp2UXqJ5Y6kclpvhvwDVTe4wRJGsxK4BjR5Z+avkG4gKhNGA6sIxA5KPJun05Out2CT200=
    file: memol-${TARGET}.zip
    skip_cleanup: true
