[workspace]
members = ["memol", "memol_util", "memol_cli", "memol_gui", "memol_vst"]
resolver = "2"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
strip = "symbols"
