[workspace]
members = ["memol", "memol_util", "memol_cli", "memol_gui", "memol_vst"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
overflow-checks = false
debug = false

[profile.release]
codegen-units = 1
lto = true
strip = true
