[workspace]
members = ["memol", "memol_cli", "memol_gui", "memol_vst"]

[profile.dev]
debug = false
incremental = false

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
