[package]
name = "memol"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]
build = "build.rs"
edition = "2018"

[dependencies]
lalrpop-util = "*"
regex = "*"

[build-dependencies]
lalrpop = "*"
