[package]
name = "memol"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]
build = "build.rs"

[dependencies]
getopts = "*"
lalrpop-util = "*"
libloading = "*"
regex = "*"

[build-dependencies]
lalrpop = "*"
