[package]
name = "memol"
edition = "2021"
build = "build.rs"

[dependencies]
lalrpop-util = { version = "*", features = ["lexer"] }
regex = "*"
serde = { version = "*", features = ["derive"] }

[build-dependencies]
lalrpop = { version = "*", features = ["lexer"] }
