[package]
name = "memol"
edition = "2024"
build = "build.rs"

[dependencies]
lalrpop-util = { version = "*", default-features = false, features = ["lexer"] }
regex = { version = "*", default-features = false }

[build-dependencies]
lalrpop = { version = "*", default-features = false, features = ["lexer"] }
