[package]
name = "memol_gui"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]

[dependencies]
getopts = "*"
gl = "*"
glutin = "*"
imgui = { path = "../imgui" }
memol = { path = ".." }

[profile.release]
lto = true
