[package]
name = "memol_vst"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]

[dependencies]
vst2 = { git = "https://github.com/overdrivenpotato/rust-vst2" }
memol = { path = "../memol" }

[lib]
crate-type = ["cdylib"]
