[package]
name = "memol_cli"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]

[dependencies]
getopts = "*"
libloading = "*"
ws = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
memol = { path = "../memol" }
