[package]
name = "memol_cli"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]
edition = "2018"
workspace = ".."

[dependencies]
serde = { version = "*", features = ["derive"] }
bincode = "*"
gumdrop = "*"
libloading = "*"
memol = { path = "../memol" }
